import localFont from 'next/font/local';

import Footer from '@clientComponents/Global/Footer';
import Header from '@clientComponents/Global/Header';

import './globals.css';

const visbyMedium = localFont({
	src: '/font/visbyMedium.otf',
	variable: '--font-body',
});

const robotoSlab = localFont({
	src: '/font/RobotoSlab.ttf',
	variable: '--font-novel-serif',
});

const visbyExtraBold = localFont({
	src: '/font/VisbyExtrabold.otf',
	variable: '--font-stroke',
});

const heyComic = localFont({
	src: '/font/HeyComic.otf',
	variable: '--font-banner',
});

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body
				className={`${visbyMedium.variable} ${visbyExtraBold.variable} ${heyComic.variable} ${robotoSlab.variable} antialiased`}
			>
				<Header />
				<div
					id="portalContainer"
					className="relative"
				>
					{children}
				</div>
				<Footer />
			</body>
		</html>
	);
}