export const notifications = [
	{
		id: 1,
		type: 'follow',
		name: 'John Doe',
		date: 'Sept 18, 2024',
		time: '9:00 PM',
		avatar: '/assets/images/HoracioAltunaSignant1.png',
		text: 'has started following you.',
	},
	{
		id: 2,
		type: 'message',
		name: 'John Doe',
		date: 'Sept 18, 2024',
		time: '9:00 PM',
		text: 'just messaged you.',
	},
	{
		id: 3,
		type: 'follow',
		name: 'John Doe',
		date: 'Sept 18, 2024',
		time: '9:00 PM',
		avatar: '/assets/images/HoracioAltunaSignant1.png',
		text: 'has started following you.',
	},
	{
		id: 4,
		type: 'message',
		name: 'John Doe',
		date: 'Sept 18, 2024',
		time: '9:00 PM',
		text: 'just messaged you.',
	},
];

export const comics = [
  {
    id: 1,
		title: "Black Panther",
    author: "Some Guy Mc.Name",
    likes: Math.floor(Math.random() * 10000000 ),
		price: 120,
    image: "/assets/images/black_panther_cover2.png",
		pages: [
		'/assets/images/image1.png',
		'/assets/images/black_panther_cover1.png',
		'/assets/images/black_panther_cover2.png',
		'/assets/images/black_panther_cover3.png',
		'/assets/images/black_panther_cover4.png',
	],
    tags: ["action", "sci-fi", "superhero"],
  },
  {
    id: 2,
		title: "Black Panther",
    author: "Some Guy Mc.Name",
    likes: Math.floor(Math.random() * 10000000 ),
		price: 120,
    image: "/assets/images/black_panther_cover1.png",
		pages: [
		'/assets/images/image1.png',
		'/assets/images/black_panther_cover1.png',
		'/assets/images/black_panther_cover2.png',
		'/assets/images/black_panther_cover3.png',
		'/assets/images/black_panther_cover4.png',
	],
    tags: ["action", "sci-fi", "superhero"],
  },
  {
    id: 3,
		title: "Black Panther",
    author: "Some Guy Mc.Name",
    likes: Math.floor(Math.random() * 10000000 ),
		price: 120,
    image: "/assets/images/black_panther_cover3.png",
		pages: [
		'/assets/images/image1.png',
		'/assets/images/black_panther_cover1.png',
		'/assets/images/black_panther_cover2.png',
		'/assets/images/black_panther_cover3.png',
		'/assets/images/black_panther_cover4.png',
	],
    tags: ["action", "sci-fi", "superhero"],
  },
  {
    id: 4,
		title: "Black Panther",
    author: "Some Guy Mc.Name",
    likes: Math.floor(Math.random() * 10000000 ),
		price: 120,
    image: "/assets/images/black_panther_cover4.png",
		pages: [
		'/assets/images/image1.png',
		'/assets/images/black_panther_cover1.png',
		'/assets/images/black_panther_cover2.png',
		'/assets/images/black_panther_cover3.png',
		'/assets/images/black_panther_cover4.png',
	],
    tags: ["action", "sci-fi", "superhero"],
  },
  {
    id: 5,
		title: "Black Panther: Wakanda",
    author: "Some Guy Mc.Name",
    likes: Math.floor(Math.random() * 10000000 ),
		price: 135,
    image: "/assets/images/black_panther_cover5.png",
		pages: [
		'/assets/images/image1.png',
		'/assets/images/black_panther_cover1.png',
		'/assets/images/black_panther_cover2.png',
		'/assets/images/black_panther_cover3.png',
		'/assets/images/black_panther_cover4.png',
	],
    tags: ["action", "adventure", "superhero"],
  },
  {
    id: 6,
		title: "Black Panther: Origins",
    author: "Some Guy Mc.Name",
    likes: Math.floor(Math.random() * 10000000 ),
		price: 110,
    image: "/assets/images/black_panther_cover8.png",
		pages: [
		'/assets/images/image1.png',
		'/assets/images/black_panther_cover1.png',
		'/assets/images/black_panther_cover2.png',
		'/assets/images/black_panther_cover3.png',
		'/assets/images/black_panther_cover4.png',
	],
    tags: ["origin", "sci-fi", "superhero"],
  },
  {
    id: 7,
		title: "Dragon Ball Z",
    author: "Some Guy Mc.Name",
    likes: Math.floor(Math.random() * 10000000 ),
		price: 125,
    image: "/assets/images/black_panther_cover6.png",
		pages: [
		'/assets/images/image1.png',
		'/assets/images/black_panther_cover1.png',
		'/assets/images/black_panther_cover2.png',
		'/assets/images/black_panther_cover3.png',
		'/assets/images/black_panther_cover4.png',
	],
    tags: ["action", "adventure", "comedy"],
  },
  {
    id: 8,
		title: "Black Panther: Vibranium",
    author: "Some Guy Mc.Name",
    likes: Math.floor(Math.random() * 10000000 ),
		price: 130,
    image: "/assets/images/black_panther_cover-7.png",
		pages: [
		'/assets/images/image1.png',
		'/assets/images/black_panther_cover1.png',
		'/assets/images/black_panther_cover2.png',
		'/assets/images/black_panther_cover3.png',
		'/assets/images/black_panther_cover4.png',
	],
    tags: ["action", "sci-fi", "adventure"],
  },
  {
    id: 9,
		title: "Black Panther: Shuri",
    author: "Some Guy Mc.Name",
    likes: Math.floor(Math.random() * 10000000 ),
		price: 115,
    image: "/assets/images/black_panther_cover4.png",
		pages: [
		'/assets/images/image1.png',
		'/assets/images/black_panther_cover1.png',
		'/assets/images/black_panther_cover2.png',
		'/assets/images/black_panther_cover3.png',
		'/assets/images/black_panther_cover4.png',
	],
    tags: ["adventure", "sci-fi", "superhero"],
  },
  {
    id: 10,
		title: "Black Panther: T'Challa",
    author: "Some Guy Mc.Name",
    likes: Math.floor(Math.random() * 10000000 ),
		price: 140,
    image: "/assets/images/black_panther_cover8.png",
		pages: [
		'/assets/images/image1.png',
		'/assets/images/black_panther_cover1.png',
		'/assets/images/black_panther_cover2.png',
		'/assets/images/black_panther_cover3.png',
		'/assets/images/black_panther_cover4.png',
	],
    tags: ["action", "drama", "superhero"],
  },
  {
    id: 11,
		title: "Black Panther: Dora Milaje",
    author: "Some Guy Mc.Name",
    likes: Math.floor(Math.random() * 10000000 ),
		price: 125,
    image: "/assets/images/black_panther_cover5.png",
		pages: [
		'/assets/images/image1.png',
		'/assets/images/black_panther_cover1.png',
		'/assets/images/black_panther_cover2.png',
		'/assets/images/black_panther_cover3.png',
		'/assets/images/black_panther_cover4.png',
	],
    tags: ["action", "warrior", "superhero"],
  },
  {
    id: 12,
		title: "Black Panther: Killmonger",
    author: "Some Guy Mc.Name",
    likes: Math.floor(Math.random() * 10000000 ),
		price: 130,
    image: "/assets/images/black_panther_cover2.png",
		pages: [
		'/assets/images/image1.png',
		'/assets/images/black_panther_cover1.png',
		'/assets/images/black_panther_cover2.png',
		'/assets/images/black_panther_cover3.png',
		'/assets/images/black_panther_cover4.png',
	],
    tags: ["villain", "action", "drama"],
  },
];

export const followerProfiles = [
  {
    id: 1,
    name: "Jason Statham",
    country: "Argentina",
    image: "/assets/images/250px-Horacio_Altuna1.png",
  },
  {
    id: 2,
    name: "Josh Berlin",
    country: "Belgium",
    image: "/assets/images/HoracioAltunaSignant1.png",
  },
  {
    id: 3,
    name: "Kim Wood",
    country: "Argentina",
    image: "/assets/images/250px-Horac.png",
  },
  {
    id: 4,
    name: "Jessica Taylor",
    country: "Belgium",
    image: "/assets/images/Dino_attanasio.png",
  },
  {
    id: 5,
    name: "Ferry Clinton",
    country: "Argentina",
    image: "/assets/images/250px-Horacio_Alt.png",
  },
  {
    id: 6,
    name: "David Bush",
    country: "Belgium",
    image: "/assets/images/Dino_attanasio17.png",
  },
  {
    id: 7,
    name: "Jason Statham",
    country: "Argentina",
    image: "/assets/images/250px-Horacio_Altuna1.png",
  },
  {
    id: 8,
    name: "Josh Berlin",
    country: "Belgium",
    image: "/assets/images/HoracioAltunaSignant1.png",
  },
  {
    id: 9,
    name: "Kim Wood",
    country: "Argentina",
    image: "/assets/images/250px-Horac.png",
  },
  {
    id: 10,
    name: "Jessica Taylor",
    country: "Belgium",
    image: "/assets/images/Dino_attanasio.png",
  },
  {
    id: 11,
    name: "Ferry Clinton",
    country: "Argentina",
    image: "/assets/images/250px-Horacio_Alt.png",
  },
  {
    id: 12,
    name: "David Bush",
    country: "Belgium",
    image: "/assets/images/250px-Horacio_Alt.png",
  },
];

export const subscriptionPlans = [
  { id: 1, type: "Weekly", coins: 1200, name: "Diamond", price: 5.99 },
  { id: 2, type: "Monthly", coins: 1000, name: "Silver", price: 32.99 },
  { id: 3, type: "Monthly", coins: 10000, name: "Gold", price: 49.99 },
];

export const products = [
  {
    id: "1",
    title: "Black Panther",
    price: 150,
    image: "/assets/images/black_panther_cover2.png",
    tags: ["BlackPanth", "BuyIt", "ReaderPanth"],
    dateAdded: "2024-03-15",
  },
  {
    id: "2",
    title: "Black Panther",
    price: 100,
    image: "/assets/images/black_panther_cover8.png",
    tags: ["BlackPanth", "BuyIt", "ReaderPanth"],
    dateAdded: "2024-03-20",
  },
  {
    id: "3",
    title: "Black Panther",
    price: 120,
    image: "/assets/images/black_panther_cover3.png",
    tags: ["BlackPanth", "BuyIt", "ReaderPanth", "comedy"],
    dateAdded: "2024-03-25",
  },
  {
    id: "4",
    title: "Black Panther",
    price: 150,
    image: "/assets/images/black_panther_cover8.png",
    tags: ["BlackPanth", "BuyIt", "ReaderPanth"],
    dateAdded: "2024-04-01",
  },
  {
    id: "5",
    title: "Black Panther",
    price: 100,
    image: "/assets/images/black_panther_cover3.png",
    tags: ["BlackPanth", "BuyIt", "ReaderPanth"],
    dateAdded: "2024-04-05",
  },
  {
    id: "6",
    title: "Black Panther",
    price: 120,
    image: "/assets/images/black_panther_cover2.png",
    tags: ["BlackPanth", "BuyIt", "ReaderPanth"],
    dateAdded: "2024-04-10",
  },
  {
    id: "7",
    title: "Black Panther",
    price: 150,
    image: "/assets/images/black_panther_cover2.png",
    tags: ["BlackPanth", "BuyIt", "ReaderPanth"],
    dateAdded: "2024-03-10",
  },
  {
    id: "8",
    title: "Black Panther",
    price: 80,
    image: "/assets/images/black_panther_cover8.png",
    tags: ["BlackPanth", "BuyIt", "ReaderPanth"],
    dateAdded: "2024-03-05",
  },
  {
    id: "9",
    title: "Black Panther",
    price: 120,
    image: "/assets/images/black_panther_cover3.png",
    tags: ["BlackPanth", "BuyIt", "ReaderPanth"],
    dateAdded: "2024-02-28",
  },
  {
    id: "10",
    title: "Black Panther",
    price: 180,
    image: "/assets/images/7dac54db.png",
    tags: ["BlackPanth", "BuyIt", "ReaderPanth"],
    dateAdded: "2024-02-20",
  },
  {
    id: "11",
    title: "Black Panther",
    price: 200,
    image: "/assets/images/27400549c0d.jpeg",
    tags: ["BlackPanth", "BuyIt", "ReaderPanth"],
    dateAdded: "2024-02-15",
  },
  {
    id: "12",
    title: "Black Panther",
    price: 150,
    image: "/assets/images/2386e4d1e02e.jpeg",
    tags: ["BlackPanth", "BuyIt", "ReaderPanth"],
    dateAdded: "2024-03-15",
  },
  {
    id: "13",
    title: "Black Panther",
    price: 100,
    image: "/assets/images/d6aab9dc4815.jpeg",
    tags: ["BlackPanth", "BuyIt", "ReaderPanth"],
    dateAdded: "2024-03-20",
  },
  {
    id: "14",
    title: "Black Panther",
    price: 120,
    image: "/assets/images/556ff.jpeg",
    tags: ["BlackPanth", "BuyIt", "ReaderPanth"],
    dateAdded: "2024-03-25",
  },
  {
    id: "15",
    title: "Black Panther",
    price: 150,
    image: "/assets/images/black_panther_cover-7.png",
    tags: ["BlackPanth", "BuyIt", "ReaderPanth"],
    dateAdded: "2024-04-01",
  },
  {
    id: "16",
    title: "Black Panther",
    price: 100,
    image: "/assets/images/black_panther_cover2.png",
    tags: ["BlackPanth", "BuyIt", "ReaderPanth"],
    dateAdded: "2024-04-05",
  },
  {
    id: "17",
    title: "Black Panther",
    price: 120,
    image: "/assets/images/black_panther_cover-7.png",
    tags: ["BlackPanth", "BuyIt", "ReaderPanth"],
    dateAdded: "2024-04-10",
  },
  {
    id: "18",
    title: "Killmonger's Return",
    price: 1195,
    image: "/assets/images/black_panther_cover6.png",
    tags: ["action", "Killmonger's Return", "Revenge", "ReaderFav"],
    dateAdded: "2024-03-15",
  },
  {
    id: "19",
    title: "The Dora Milaje",
    price: 715,
    image: "/assets/images/black_panther_cover4.png",
    tags: ["action", "The Dora Milaje", "Elite", "BuyNow"],
    dateAdded: "2024-03-15",
  },
  {
    id: "20",
    title: "Panther vs. Doom",
    price: 875,
    image: "/assets/images/black_panther_cover5.png",
    tags: ["action", "Panther vs. Doom", "Rivalry", "PowerPlay"],
    dateAdded: "2024-03-15",
  },
  {
    id: "21",
    title: "Black Panther",
    price: 1499,
    image: "/assets/images/black_panther_cover2.png",
    tags: ["action", "Black Panther", "Classic", "TopRated"],
    dateAdded: "2024-03-15",
  },
  {
    id: "22",
    title: "Wakanda Forever",
    price: 460,
    image: "/assets/images/black_panther_cover1.png",
    tags: ["action", "Wakanda Forever", "Unity", "Hope"],
    dateAdded: "2024-03-15",
  },
  {
    id: "23",
    title: "King T'Challa",
    price: 910,
    image: "/assets/images/black_panther_cover3.png",
    tags: ["action", "King T'Challa", "Wisdom", "Power"],
    dateAdded: "2024-03-15",
  },
  {
    id: "24",
    title: "Vibranium Hunt",
    price: 800,
    image: "/assets/images/black_panther_cover7.png",
    tags: ["action", "Vibranium Hunt", "Secrets", "Tech"],
    dateAdded: "2024-03-15",
  },
  {
    id: "25",
    title: "Shuri's Legacy",
    price: 540,
    image: "/assets/images/black_panther_cover4.png",
    tags: ["action", "Shuri's Legacy", "Future", "Leader"],
    dateAdded: "2024-03-15",
  },
  {
    id: "26",
    title: "Battle for Wakanda",
    price: 1320,
    image: "/assets/images/black_panther_cover6.png",
    tags: ["action", "Battle for Wakanda", "Epic", "Defenders"],
    dateAdded: "2024-03-15",
  },
  {
    id: "27",
    title: "The Rise of Bast",
    price: 333,
    image: "/assets/images/black_panther_cover5.png",
    tags: ["action", "The Rise of Bast", "Gods", "Legacy"],
    dateAdded: "2024-03-15",
  },
  {
    id: "28",
    title: "Killmonger's Return",
    price: 1250,
    image: "/assets/images/black_panther_cover1.png",
    tags: ["action", "Killmonger's Return", "Danger", "Conflict"],
    dateAdded: "2024-03-15",
  },
  {
    id: "29",
    title: "The Dora Milaje",
    price: 640,
    image: "/assets/images/black_panther_cover2.png",
    tags: ["action", "The Dora Milaje", "Guardians", "Sisters"],
    dateAdded: "2024-03-15",
  },
  {
    id: "30",
    title: "Panther vs. Doom",
    price: 777,
    image: "/assets/images/black_panther_cover3.png",
    tags: ["action", "Panther vs. Doom", "Enemies", "Showdown"],
    dateAdded: "2024-03-15",
  },
  {
    id: "31",
    title: "Black Panther",
    price: 1300,
    image: "/assets/images/black_panther_cover4.png",
    tags: ["action", "Black Panther", "BuyIt", "Fav"],
    dateAdded: "2024-03-15",
  },
  {
    id: "32",
    title: "Wakanda Forever",
    price: 815,
    image: "/assets/images/black_panther_cover5.png",
    tags: ["action", "Wakanda Forever", "Heroism", "Culture"],
    dateAdded: "2024-03-15",
  },
  {
    id: "33",
    title: "King T'Challa",
    price: 1010,
    image: "/assets/images/black_panther_cover6.png",
    tags: ["action", "King T'Challa", "Wisdom", "Throne"],
    dateAdded: "2024-03-15",
  },
  {
    id: "34",
    title: "Vibranium Hunt",
    price: 390,
    image: "/assets/images/black_panther_cover7.png",
    tags: ["action", "Vibranium Hunt", "Clue", "Danger"],
    dateAdded: "2024-03-15",
  },
  {
    id: "35",
    title: "Shuri's Legacy",
    price: 455,
    image: "/assets/images/black_panther_cover1.png",
    tags: ["action", "Shuri's Legacy", "Smart", "NextGen"],
    dateAdded: "2024-03-15",
  },
  {
    id: "36",
    title: "Battle for Wakanda",
    price: 1280,
    image: "/assets/images/black_panther_cover2.png",
    tags: ["action", "Battle for Wakanda", "Showdown", "Heroes"],
    dateAdded: "2024-03-15",
  },
  {
    id: "37",
    title: "The Rise of Bast",
    price: 299,
    image: "/assets/images/black_panther_cover3.png",
    tags: ["action", "The Rise of Bast", "Spirit", "Origin"],
    dateAdded: "2024-03-15",
  },
  {
    id: "38",
    title: "Killmonger's Return",
    price: 925,
    image: "/assets/images/black_panther_cover4.png",
    tags: ["action", "Killmonger's Return", "Chaos", "Enemy", "sci-fi"],
    dateAdded: "2025-07-02",
  },
  {
    id: "39",
    title: "The Dora Milaje",
    price: 595,
    image: "/assets/images/black_panther_cover5.png",
    tags: ["action", "The Dora Milaje", "Guard", "Sisterhood", 'action'],
    dateAdded: "2025-07-15",
  },
  {
    id: "40",
    title: "Panther vs. Doom",
    price: 1500,
    image: "/assets/images/black_panther_cover6.png",
    tags: ["Panther vs. Doom", "Clash", "MustRead", "horror"],
    dateAdded: "2025-06-15",
  },
];

export const subscribed = [
  {
    id: 1,
    type: "follow",
    name: "John Doe",
    date: "Sept 18, 2024",
    time: "9:00 PM",
    avatar: "/assets/images/HoracioAltunaSignant1.png",
    text: "has started following you.",
  },
  {
    id: 2,
    type: "message",
    name: "John Doe",
    date: "Sept 18, 2024",
    time: "9:00 PM",
    text: "just messaged you.",
  },
  {
    id: 3,
    type: "follow",
    name: "John Doe",
    date: "Sept 18, 2024",
    time: "9:00 PM",
    avatar: "/assets/images/HoracioAltunaSignant1.png",
    text: "has started following you.",
  },
  {
    id: 4,
    type: "message",
    name: "John Doe",
    date: "Sept 18, 2024",
    time: "9:00 PM",
    text: "just messaged you.",
  },
];

export const followingProfiles = [
  {
    id: 1,
    name: "Horacio Altuna",
    description: "- (El Loco Chavez)",
    country: "Argentina",
    followers: "2.2M",
    image: "/assets/images/250px-Horacio_Altuna_Signant_-_1.png",
  },
  {
    id: 2,
    name: "Dino Attanasio",
    description: "Belgian of Italian descent",
    country: "Belgium",
    followers: "2.2M",
    image: "/assets/images/Dino_attanasio_-1652531977.png",
  },
  {
    id: 3,
    name: "Horacio Altuna",
    description: "- (El Loco Chavez)",
    country: "Argentina",
    followers: "2.2M",
    image: "/assets/images/250px-Horacio_Altuna_Signant_-_1.png",
  },
  {
    id: 4,
    name: "Dino Attanasio",
    description: "Belgian of Italian descent",
    country: "Belgium",
    followers: "2.2M",
    image: "/assets/images/Dino_attanasio_-1652531977.png",
  },
  {
    id: 5,
    name: "Horacio Altuna",
    description: "- (El Loco Chavez)",
    country: "Argentina",
    followers: "2.2M",
    image: "/assets/images/250px-Horacio_Altuna_Signant_-_1.png",
  },
  {
    id: 6,
    name: "Dino Attanasio",
    description: "Belgian of Italian descent",
    country: "Belgium",
    followers: "2.2M",
    image: "/assets/images/Dino_attanasio_-1652531977.png",
  },
];

export const messagesMock = [
  {
    id: 1,
    text: "Yes of course, Are there problems with your job?",
    sender: "me",
    time: "Today 11:53",
    status: "read",
  },
  {
    id: 2,
    text: "Morning Eten Hunt, I have a question about my job!",
    sender: "other",
    time: "Today 11:52",
  },
  {
    id: 3,
    text: "Good question. How about just discussing it?",
    sender: "me",
    time: "Today 11:55",
    status: "read",
  },
  {
    id: 4,
    text: "Morning Eten Hunt, I have a question about my job!",
    sender: "other",
    time: "Today 11:52",
  },
  {
    id: 5,
    text: "What are the points that are important to get the perfect result of my assignment?",
    sender: "other",
    time: "Today 11:54",
  },
  {
    id: 6,
    text: "Yes of course, Are there problems with your job?",
    sender: "me",
    time: "Today 11:53",
    status: "read",
  },
  {
    id: 7,
    text: "",
    sender: "other",
    time: "Today 11:54",
    isAudio: true,
    duration: "0:12",
  },
];

export const conversationsMock = [
  {
    id: 1,
    name: "Eten Hunt",
    message: "Thank you very much. I'm glad...",
    time: "1 hour ago",
    status: "read",
  },
  {
    id: 2,
    name: "Eten Hunt",
    message: "Thank you very much. I'm glad...",
    time: "1 hour ago",
    status: "unread",
  },
  {
    id: 3,
    name: "Eten Hunt",
    message: "Thank you very much. I'm glad...",
    time: "1 hour ago",
    status: "read",
  },
  {
    id: 4,
    name: "Eten Hunt",
    message: "Thank you very much. I'm glad...",
    time: "1 hour ago",
    status: "unread",
  },
  {
    id: 5,
    name: "Eten Hunt",
    message: "Thank you very much. I'm glad...",
    time: "1 hour ago",
    status: "read",
  },
  {
    id: 6,
    name: "Eten Hunt",
    message: "Thank you very much. I'm glad...",
    time: "1 hour ago",
    status: "read",
  },
  {
    id: 7,
    name: "Eten Hunt",
    message: "Thank you very much. I'm glad...",
    time: "1 hour ago",
    status: "read",
  },
];



export const mockedChapter = {
	title: 'Some novel',
	pharagraphs: [
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam in risus id magna facilisis pretium. Phasellus ullamcorper lorem vel sapien viverra, nec euismod augue posuere. Vestibulum id lorem sed arcu fringilla porttitor vitae ac libero. Curabitur sed tempor magna, vitae cursus ligula.",
  "Sed consequat, erat nec porta sodales, est erat cursus purus, sit amet convallis mi purus vitae justo. Integer finibus turpis in sapien laoreet, nec aliquam velit varius. Donec a felis et lacus tincidunt laoreet. Duis tincidunt tortor at bibendum tincidunt. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.",
  "Praesent euismod, justo id ultricies convallis, lectus velit ultricies metus, nec egestas eros elit sed felis. Aliquam erat volutpat. Suspendisse malesuada augue non eros porta, id vestibulum lacus accumsan. Proin at ligula nec orci congue commodo sit amet vitae justo. Morbi fermentum tincidunt lacus, vitae consequat velit volutpat eget.",
  "Curabitur mattis metus ut turpis tincidunt, et lacinia nulla tincidunt. Suspendisse fermentum, metus sit amet accumsan luctus, sem leo malesuada ipsum, id dapibus nunc elit nec lectus. Nam ac ex vitae odio posuere tincidunt at in orci. Nulla facilisi. Cras at dictum felis, vel pulvinar purus.",
  "Vestibulum ut sapien sit amet purus mattis faucibus. Mauris fermentum justo at ligula hendrerit, non porttitor mauris accumsan. Duis a lacus a neque interdum egestas. Integer euismod tortor vitae dui imperdiet, a tincidunt nisl rhoncus. Donec tincidunt lacus vitae elit luctus fringilla vel non lorem.",
  "Sed consequat, erat nec porta sodales, est erat cursus purus, sit amet convallis mi purus vitae justo. Integer finibus turpis in sapien laoreet, nec aliquam velit varius. Donec a felis et lacus tincidunt laoreet. Duis tincidunt tortor at bibendum tincidunt. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.",
  "Praesent euismod, justo id ultricies convallis, lectus velit ultricies metus, nec egestas eros elit sed felis. Aliquam erat volutpat. Suspendisse malesuada augue non eros porta, id vestibulum lacus accumsan. Proin at ligula nec orci congue commodo sit amet vitae justo. Morbi fermentum tincidunt lacus, vitae consequat velit volutpat eget.",
  "Curabitur mattis metus ut turpis tincidunt, et lacinia nulla tincidunt. Suspendisse fermentum, metus sit amet accumsan luctus, sem leo malesuada ipsum, id dapibus nunc elit nec lectus. Nam ac ex vitae odio posuere tincidunt at in orci. Nulla facilisi. Cras at dictum felis, vel pulvinar purus.",
  "Vestibulum ut sapien sit amet purus mattis faucibus. Mauris fermentum justo at ligula hendrerit, non porttitor mauris accumsan. Duis a lacus a neque interdum egestas. Integer euismod tortor vitae dui imperdiet, a tincidunt nisl rhoncus. Donec tincidunt lacus vitae elit luctus fringilla vel non lorem.",
  "Sed consequat, erat nec porta sodales, est erat cursus purus, sit amet convallis mi purus vitae justo. Integer finibus turpis in sapien laoreet, nec aliquam velit varius. Donec a felis et lacus tincidunt laoreet. Duis tincidunt tortor at bibendum tincidunt. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.",
  "Praesent euismod, justo id ultricies convallis, lectus velit ultricies metus, nec egestas eros elit sed felis. Aliquam erat volutpat. Suspendisse malesuada augue non eros porta, id vestibulum lacus accumsan. Proin at ligula nec orci congue commodo sit amet vitae justo. Morbi fermentum tincidunt lacus, vitae consequat velit volutpat eget.",
  "Curabitur mattis metus ut turpis tincidunt, et lacinia nulla tincidunt. Suspendisse fermentum, metus sit amet accumsan luctus, sem leo malesuada ipsum, id dapibus nunc elit nec lectus. Nam ac ex vitae odio posuere tincidunt at in orci. Nulla facilisi. Cras at dictum felis, vel pulvinar purus.",
  "Vestibulum ut sapien sit amet purus mattis faucibus. Mauris fermentum justo at ligula hendrerit, non porttitor mauris accumsan. Duis a lacus a neque interdum egestas. Integer euismod tortor vitae dui imperdiet, a tincidunt nisl rhoncus. Donec tincidunt lacus vitae elit luctus fringilla vel non lorem.",
  "Sed consequat, erat nec porta sodales, est erat cursus purus, sit amet convallis mi purus vitae justo. Integer finibus turpis in sapien laoreet, nec aliquam velit varius. Donec a felis et lacus tincidunt laoreet. Duis tincidunt tortor at bibendum tincidunt. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.",
  "Praesent euismod, justo id ultricies convallis, lectus velit ultricies metus, nec egestas eros elit sed felis. Aliquam erat volutpat. Suspendisse malesuada augue non eros porta, id vestibulum lacus accumsan. Proin at ligula nec orci congue commodo sit amet vitae justo. Morbi fermentum tincidunt lacus, vitae consequat velit volutpat eget.",
  "Curabitur mattis metus ut turpis tincidunt, et lacinia nulla tincidunt. Suspendisse fermentum, metus sit amet accumsan luctus, sem leo malesuada ipsum, id dapibus nunc elit nec lectus. Nam ac ex vitae odio posuere tincidunt at in orci. Nulla facilisi. Cras at dictum felis, vel pulvinar purus.",
  "Vestibulum ut sapien sit amet purus mattis faucibus. Mauris fermentum justo at ligula hendrerit, non porttitor mauris accumsan. Duis a lacus a neque interdum egestas. Integer euismod tortor vitae dui imperdiet, a tincidunt nisl rhoncus. Donec tincidunt lacus vitae elit luctus fringilla vel non lorem.",
  "Sed consequat, erat nec porta sodales, est erat cursus purus, sit amet convallis mi purus vitae justo. Integer finibus turpis in sapien laoreet, nec aliquam velit varius. Donec a felis et lacus tincidunt laoreet. Duis tincidunt tortor at bibendum tincidunt. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.",
  "Praesent euismod, justo id ultricies convallis, lectus velit ultricies metus, nec egestas eros elit sed felis. Aliquam erat volutpat. Suspendisse malesuada augue non eros porta, id vestibulum lacus accumsan. Proin at ligula nec orci congue commodo sit amet vitae justo. Morbi fermentum tincidunt lacus, vitae consequat velit volutpat eget.",
  "Curabitur mattis metus ut turpis tincidunt, et lacinia nulla tincidunt. Suspendisse fermentum, metus sit amet accumsan luctus, sem leo malesuada ipsum, id dapibus nunc elit nec lectus. Nam ac ex vitae odio posuere tincidunt at in orci. Nulla facilisi. Cras at dictum felis, vel pulvinar purus.",
  "Vestibulum ut sapien sit amet purus mattis faucibus. Mauris fermentum justo at ligula hendrerit, non porttitor mauris accumsan. Duis a lacus a neque interdum egestas. Integer euismod tortor vitae dui imperdiet, a tincidunt nisl rhoncus. Donec tincidunt lacus vitae elit luctus fringilla vel non lorem."
]

}

export const mockedNovel = [{...mockedChapter, title: 'chapter 1'}, {...mockedChapter, title: 'chapter 2'}, {...mockedChapter, title: 'chapter 3'}, {...mockedChapter, title: 'chapter 4'}, {...mockedChapter, title: 'chapter 5'}, {...mockedChapter, title: 'chapter 6'}]
export const extraLargeNovel = {title: "Some Novel Title", chapters: [...mockedNovel, ...mockedNovel, ...mockedNovel]}
